Code/BootStrap7/BootStrap4/Models/TaiKhoan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootStrap4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.DangKyTins = new HashSet<DangKyTin>();
        }
    
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public Nullable<bool> Quyen { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKyTin> DangKyTins { get; set; }
    }
}

Code/BootStrap7/BootStrap4/Models/Tai_Khoan/TaiKhoanInterface.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BootStrap4.Models.Tai_Khoan
{
    interface TaiKhoanInterface
    {
        IEnumerable<TaiKhoanModel> GetListTK();
        TaiKhoanModel GetTaiKhoan(string tenTK);

        TaiKhoanModel GetTaiKhoanByTK(string tenTK);

        string GetTenTK();
        string GetMatKhau();

        string GetHoTen(string tenTK);

        TaiKhoanModel Create(string tenTk, string matKhau, string quyen, string nguoiTao, DateTime ngayTao);

        TaiKhoanModel Update(string tenTk, string matKhau, string quyen);

        TaiKhoanModel Delete(string tenTk);

        bool Login(string tenTK, string mK);

        bool Logout();

        

        
    }
}

Code/BootStrap7/BootStrap4/Models/Tai_Khoan/TaiKhoanModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BootStrap4.Models.Tai_Khoan
{
    public class TaiKhoanModel
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Quyen { get; set; }

        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
    }
}

Code/BootStrap7/BootStrap4/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BootStrap4.Models;
using BootStrap4.Models.Dang_Ky_Tin;
using BootStrap4.Models.Tai_Khoan;
using BootStrap4.Models.Mon_Hoc;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace BootStrap4.Controllers
{
    public class MainController : Controller
    {
        DangKyTinModel dangKyTinModel = new DangKyTinModel();
        MonHocModel monHocModel = new MonHocModel();
        TaiKhoanModel taiKhoanModel = new TaiKhoanModel();

        // GET: Main
        [HttpGet]
        public ActionResult MainIndex()
        {
            return View();
        }

        public ActionResult DangKyTinChi(int page = 1, int pageSize = 10)
        {
            try
            {
                string tenTK = Session["user"].ToString();
                var model = new DangKyTinHandler().GetDangKyTin(tenTK).ToPagedList(page, pageSize);
                return View(model);
            }
            catch(Exception e)
            {
                return Content(e.Message);
            }
            
            
        }
        public ActionResult FilterDKT(string searchString, int page = 1, int pageSize = 10)
        {
            try
            {
                string tenTK = Session["user"].ToString();
                var model = new DangKyTinHandler().FilterDKT(tenTK, searchString ).ToPagedList(page, pageSize);
                return View("DangKyTinChi", model);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        public ActionResult MethodDKT(string submitButton, MonHoc monHoc, FormCollection frmCollection, string searchString)
        {
            switch (submitButton)
            {
                case "Hủy đăng ký":
                    return DeleteDKT(frmCollection);
                case "Search":
                    return FilterDKT(searchString);
                case "Xuất danh sách":
                    return DownPDFDKT();
                case "Refresh":
                    return RedirectToAction("DangKyTinChi");
                default:
                    return (View("Index"));
            }
        }

        public ActionResult QuanLyMonHoc(int page = 1, int pageSize = 10)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                var modelMH = new MonHocHandler().GetMonHocs(tenTK).OrderBy(x => x.MaMon).ToPagedList(page, pageSize);
                return View(modelMH);
            }
            catch(Exception ex)
            {
                return Content(ex.Message);
            }
            
        }
        
        
        public ActionResult MethodMonHoc(string submitButton, MonHoc monHoc, FormCollection frmCollection, 
                                         string searchString,string maMon, string tenMon)
        {
            switch (submitButton)
            {
                case "Đăng ký":
                    return CreateDKT(frmCollection);
                case "Tạo":
                    return (View("CreateMH"));
                case "Sửa":
                    return EditMonHoc(frmCollection, monHoc);
                case "Capnhat":
                    return UpdateMonHoc2(maMon, tenMon);
                case "Xóa":
                    return DeleteMonHoc(frmCollection, monHoc);
                case "Search":
                    return FilterMonHoc(searchString);
                case "Refresh":
                    return RedirectToAction("QuanLyMonHoc");
                case "Xuất danh sách":
                    return DownPDFMH();
                default:
                    return View("Index");
            }
        }

        [HttpPost]
        public JsonResult FindMH(int Id)
        {
            try
            {
                var mh = new MonHocHandler().GetMonHocById(Id);
                ViewBag.tenMon = mh.TenMon;
                return Json(mh);
            }
            catch (Exception e)
            {
                return null;
            }
            
        }
        public ActionResult CreateMH(int maMon, string tenMon)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                var tk = new TaiKhoanHandler().GetHoTen(tenTK);
                var result = new MonHocHandler().CreateSubject(maMon, tenMon, tk, DateTime.Now);
                return RedirectToAction("QuanLyMonHoc");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        public ActionResult FilterMonHoc(string searchString, int page = 1, int pageSize = 10)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                var modelMH = new MonHocHandler().FilterSubject(tenTK, searchString).OrderBy(x => x.MaMon).ToPagedList(page, pageSize);
                return View("QuanLyMonHoc",modelMH);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            
        }
        public ActionResult CreateMonHoc(MonHoc monHoc)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                var tk = new TaiKhoanHandler().GetHoTen(tenTK);
                var result = new MonHocHandler().CreateSubject(monHoc.MaMon, monHoc.TenMon, tk, DateTime.Now);
                return RedirectToAction("QuanLyMonHoc");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        public ActionResult EditMonHoc(FormCollection frmCollection, MonHoc monHoc)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                string[] ids = frmCollection["checkboxid"].Split(new char[] { ',' });
                MonHocHandler mh = new MonHocHandler();
                if (ids.Length > 1)
                {
                    return RedirectToAction("QuanLyMonHoc");
                }
                else
                {
                    foreach (string id in ids)
                    {
                        monHoc.MaMon = int.Parse(id);
                        monHoc.TenMon = new MonHocHandler().getNameSubject(int.Parse(id));
                    }
                    return PartialView("PopUpEditMonhoc", monHoc);
                }
            }
            catch(Exception ex)
            {
                return Content(ex.Message);
            }
        }
        [HttpPost]
        public ActionResult UpdateMonHoc2(string maMon,string tenMon)
        {
            try
            { 
                string tenTK = Session["User"].ToString();
                var tk = new TaiKhoanHandler().GetHoTen(tenTK);
                var result = new MonHocHandler().UpdateSubject(int.Parse(maMon),tenMon, tk, DateTime.Now);
                return RedirectToAction("QuanLyMonHoc");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        public ActionResult UpdateMonHoc(MonHoc monHoc)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                var tk = new TaiKhoanHandler().GetHoTen(tenTK);
                var result = new MonHocHandler().UpdateSubject(monHoc.MaMon, monHoc.TenMon, tk, DateTime.Now);
                return RedirectToAction("QuanLyMonHoc");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
        }
        
        public ActionResult DeleteMonHoc(FormCollection frmCollection, MonHoc monHoc)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                string[] ids = frmCollection["checkboxid"].Split(new char[] { ',' });
                MonHocHandler mh = new MonHocHandler();
                foreach (string id in ids)
                {
                    var result = new MonHocHandler().DeleteSubject(int.Parse(id));
                }
                return RedirectToAction("QuanLyMonHoc");
            }
            catch(Exception e)
            {
                return Content(e.Message);
            }
        }
        public bool DeleteMH(int Id)
        {
            try
            {
                var result = new MonHocHandler().DeleteSubject(Id);
                if (result == true)
                {
                    return true;
                }
                else return false;
            }catch(Exception e)
            {
                return false;
            }
        }
        public bool CreateDK(int Id)
        {
            try
            {
                string tenTK = Session["User"].ToString();
                var tk = new TaiKhoanHandler().GetHoTen(tenTK);
                var result = new DangKyTinHandler().CreateDKT(Id, tenTK, tk, DateTime.Now);
                if (result == null)
                {
                    return false;
                }
                else
                {
                    return true;
                }
             
            }
            catch (Exception ex)
            {
                return false;
            }
        }
        public ActionResult CreateDKT(FormCollection frmCollection)
        {
            //try
            //{
                string tenTK = Session["User"].ToString();
               
                string[] ids = frmCollection["checkboxid"].Split(new char[] { ',' });
                var tk = new TaiKhoanHandler().GetHoTen(tenTK);
                var dkt = new DangKyTinHandler();
                foreach (string id in ids)
                {
                    var result = dkt.CreateDKT(int.Parse(id), tenTK, tk, DateTime.Now);
                    if (result == null)

Code/BootStrap7/BootStrap4/Controllers/TaiKhoanController.cs
using BootStrap4.Models.Tai_Khoan;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BootStrap4.Models;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace BootStrap4.Controllers
{
    public class TaiKhoanController : Controller
    {
        // GET: TaiKhoan

        public ActionResult QuanLyTaiKhoan(int page = 1, int pageSize = 10)
        {
            var model = new TaiKhoanHandler().GetListTK().ToPagedList(page, pageSize);
            return View(model);
        }
        public ActionResult UpdateTK(string tentk, string matkhau, string quyen)
        {
            return View();
        }

        public ActionResult CreateTK(string tentk, string matkhau, string quyen)
        {
            return View();
        }

        public ActionResult DelTK(string tentk)
        {
            return View();
        }

        public ActionResult Download_PDF()
        {
            dtbtt1Entities context = new dtbtt1Entities();

            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Report"), "ReportTK.rpt"));
            rd.SetDataSource(context.TaiKhoans.Select(c => new
            {
                TenTaiKhoan = c.TenTaiKhoan,
                MatKhau = c.MatKhau,
                Hoten = c.HoTen
               
            }).ToList());
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            //rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            //rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            //rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA5;
            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "DSTaiKhoan.pdf");
        }
        
    }
}

Code/BootStrap7/BootStrap4/Views/TaiKhoan/QuanLyTaiKhoan.cshtml
@model PagedList.IPagedList<BootStrap4.Models.Tai_Khoan.TaiKhoanModel>
@using PagedList.Mvc;


@{
    ViewBag.Title = "Quản lý Tài Khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        .overlay {
            background-color: #4268d6;
            opacity: 50%;
            position: absolute;
            display: none;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }

        .popup {
            position: fixed;
            z-index: 99;
            vertical-align: central;
            display: none;
            margin-left: 17%;
        }
    </style>
    <link href="~/Public/css/sb-admin-2.min.css" rel="stylesheet">
</head>


<html>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h4 class="m-0 font-weight-bold text-primary text-center">Quản lý tài khoản</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                @using (Html.BeginForm("MethodMonHoc", "Main", FormMethod.Post))
                                {
                                    <div class="w-100">
                                        <div class="mb-2 col-2 text-left float-left">
                                            <input type="text" class=" form-control bg-light border-0 small" placeholder="Search for..."
                                                   aria-label="Search" aria-describedby="basic-addon2" name="searchString">
                                        </div>
                                        <div class="float-left">
                                            <button class="btn btn-primary" name="submitButton" value="Search">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>

                                        </div>
                                        <div class="ml-1 float-left">
                                            <button class="btn btn-primary" name="submitButton" value="Refresh">
                                                <i class="fa-solid fa-arrows-rotate"></i>
                                            </button>
                                        </div>
                                    </div>
                                }
                                <div class="float-right mr-2">
                                    <a href="@Url.Action("Download_PDF","TaiKhoan")" " target="_blank" class="btn btn-primary" style="margin-top:20px;">Xuất dữ liệu</a>
                                    <input type="submit" class="btn btn-primary" onclick="Create()" value="Tạo">
                                </div>



                                @using (Html.BeginForm("MethodTaiKhoan", "TaiKhoan", FormMethod.Post))
                                {
                                    <div class="float-right mr-2">
                                        <input type="submit" name="submitButton" class="btn btn-primary" value="Xóa">
                                    </div>
                                    <div class="float-right mr-2">
                                        <input type="submit" name="submitButton" class="btn btn-primary" value="Xuất danh sách">
                                    </div>
                                    <table class="table table-bordered te text-center" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr role="row">
                                                <th class="col-1 ">
                                                    <input type="checkbox" onClick="selectall(this)" />
                                                </th>
                                                <th>Tên tài khoản</th>
                                                <th>Mật khẩu</th>
                                                <th>Quyền</th>
                                                <th class="col-2">Chọn</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (int i = 0; i < Model.Count(); i++)
                                            {
                                                <tr>
                                                    <td>
                                                        <input type="checkbox" class="CheckboxId" value="@Model[i].TenTaiKhoan" id="checkboxid"
                                                               name="checkboxid" />
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(Model => Model[i].TenTaiKhoan, new { @name = "TenTaiKhoan" })
                                                        @Html.HiddenFor(Model => Model[i].TenTaiKhoan)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(Model => Model[i].MatKhau, new { @name = "MatKhau" })
                                                        @Html.HiddenFor(Model => Model[i].MatKhau)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(Model => Model[i].Quyen, new { @name = "Quyen" })
                                                        @Html.HiddenFor(Model => Model[i].Quyen)
                                                    </td>
                                                    <td>
                                                        <span>
                                                            <a href="#" class="btn btn-primary btn-user btnEdit" data-target="#myModal" onclick="Edit(@Model[i].TenTaiKhoan)">Edit</a>
                                                            <a href="#" class="btn btn-danger btn-user btnDelete" data-target="#delModal" onclick="Delete(@Model[i].TenTaiKhoan)">Delete</a>
                                                        </span>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>

                                    <div class="float-left col-sm-1">
                                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                                    </div>

                                    <div class="float-right  ">
                                        @Html.PagedListPager(Model, page => Url.Action("QuanLyTaiKhoan", new { @page }), new PagedListRenderOptions
                                           {
                                               LiElementClasses = new string[] { "paginate_button page-item" },
                                           })
                                    </div>

                                }

                            </div>
                        </div>
                    </div>
                </div>
                <script src="~/Scripts/jquery-3.3.1.min.js"></script>
                <script src="~/Scripts/bootstrap.min.js"></script>

            </div>
        </div>
        <div id="Fade_area" class="overlay">
        </div>
        @*<div id="createTkModal" class="popup">
            @Html.Partial("~/Views/Main/PCreateTK.cshtml")
        </div>
        <div id="delTkModal" class="popup">
            @Html.Partial("~/Views/Main/PDelTK.cshtml")
        </div>
        <div id="editTkModal" class="popup">
            @Html.Partial("~/Views/Main/PEdit.cshtml")
        </div>*@
    </div>

    <script>
        $(document).ready(function () {
            $("#Cancel").click(function () {
                $(".overlay").removeAttr("style");
                $(".popup").removeAttr("style");
                //$("#Fade_area").removeAttr("style");
                //$(".partial, #myModal").removeAttr("style");
                //$(".partial,#delModal").removeAttr("style");
                //$(".partial,#regisModal").removeAttr("style");

            });
            $("#btnClose").click(function () {
                $(".overlay").removeAttr("style");
                $(".popup").removeAttr("style");
                //$("#Fade_area").removeAttr("style");
                //$("#myModal").removeAttr("style");
                //$("#delModal").removeAttr("style");
                //$("#regisModal").removeAttr("style");
            });
        });
        var Edit = function (id) {
            $.ajax({
                type: 'POST',
                url: "/Main/GetTK",
                data: { Id: id },
                success: function (data) {
                    $("#tenTK").val(data.TenTK)
                    $("#mK").val(data.MatKhau)
                    $("#quyen").val(data.Quyen)
                }
            });
            $("#Fade_area ,#editTkModal").fadeIn();
        }
        var Update = function () {
            tentk   = $("#tenTK").val()
            matkhau = $("#mK").val()
            quyen   = $("#quyen").val()
            $.ajax({
                type: 'POST',
                url: "/Main/UpdateTK",
                data: { maMon: id, tenMon: tenmon },
                success: function (data) {
                    $("#Fade_area").removeAttr("style");
                    $("#editModal").removeAttr("style");
                    $("#page-top").load("/TaiKhoan/QuanLyTaiKhoan");
                }
            });
        }

        var Delete = function (id) {
            $.ajax({
                type: 'POST',
                url: "/Main/FindMH",
                data: { Id: id },
                success: function (data) {
                    $("#PopUpDelMaMon").val(data.MaMon)
                    $("#PopUpDelTenMon").val(data.TenMon)
                }
            });
            $("#Fade_area ,#delModal").fadeIn();
        }

        var DeleteMhYes = function () {
            id = $("#PopUpDelMaMon").val()
            $.ajax({
                type: 'POST',
                url: "/Main/DeleteMH",
                data: { Id: id },
                success: function (data) {
                    $("#Fade_area").removeAttr("style");
                    $("#myModal").removeAttr("style");
                    $("#page-top").load("/Main/QuanLyMonHoc");
                }
            });
        }

        var Regis = function (id) {
            $.ajax({
                type: 'POST',
                url: "/Main/FindMH",
                data: { Id: id },
                success: function (data) {
                    $("#PopUpMaMon").val(data.MaMon)
                    $("#PopUpTenMon").val(data.TenMon)
                }
            });
            $("#Fade_area,#regisModal").fadeIn();
        }

        var RegisMhYes = function () {
            id = $("#PopUpMaMon").val()
            $.ajax({
                type: 'POST',
                url: "/Main/CreateDK",
                data: { Id: id },
                success: function (data) {
                    $("#Fade_area").removeAttr("style");
                    $("#regisModal").removeAttr("style");
                    $("#page-top").load("/Main/QuanLyMonHoc");
                }
            });
        }
        var Create = function () {
            $("#Fade_area ,#createModal").fadeIn();
        }
        var CreateMH = function () {
            id = $("#PCreateMaMon").val()
            tenMon = $("#PCreateTenMon").val()
            $.ajax({
                type: 'POST',
                url: "/Main/CreateMH",
                data: { maMon: id, tenMon: tenMon },
                success: function (data) {
                    $("#Fade_area").removeAttr("style");
                    $("#createModal").removeAttr("style");
                    $("#page-top").load("/Main/QuanLyMonHoc");
                }
            });
        }
    </script>
</body>

</html>